// generateCatalog.js
const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');
const files = fs.readdirSync(dataDir, { recursive: true }).filter(f => f.includes('dcat'));

const catalog = files.map((file) => {
  const filePath = path.join(dataDir, file);
  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const id = path.basename(file, '.json-ld.json');
  return { id, ...content };
});

const output = `// AUTO-GENERATED by generateCatalog.js
export const catalog = ${JSON.stringify(catalog, null, 2)};`;

fs.writeFileSync(path.join(__dirname, 'catalog.js'), output);
console.log('catalog.js generated.');